---
- name: run Python script
  hosts: all
  vars:
    ansible_python_interpreter: C:/Program Files/Python311/python.exe
  tasks:
    - name: run hello.py script
      command: python C:/Users/CN331870/Documents/hello.py
