---
- name: run Python script
  hosts: all
  delegate_to: localhost
  vars:
    ansible_python_interpreter: '/usr/bin/env'
  tasks:
    - name: run hello.py script
      win_command: python C:/Users/CN331870/Documents/sqldb.py
      register: output
      
    - name: show output
      debug: 
        var: output.stdout_lines
